#!/bin/sh
if [ $# -eq 0 ] 
then
	echo "ERROR:
1.PROVIDE ABSOLUTE/RELATIVE PATH FOR DIRECTORY CONTAINING TIFF FILES.
2.PROVIDE ABSOLUTE/RELATIVE PATH TO DIRECTORY FOR OUTPUT.[OPTIONAL]"
	exit
elif [ $# -eq 1 ] 
then 
	echo "ERROR:
1.PROVIDE ABSOLUTE/RELATIVE PATH TO DIRECTORY FOR OUTPUT."
	HTML_PATH=`pwd`/HTML_FILES
	GIF_PATH=`pwd`/GIF_FILES
	JPEG_PATH=`pwd`/JPEG_FILES
elif [ $# -eq 2 ]
then
	JPEG_PATH=$2/JPEG_FILES
	HTML_PATH=$2/HTML_FILES
	GIF_PATH=$2/GIF_FILES
else
	echo "ERROR:
1.PROVIDE ABSOLUTE/RELATIVE PATH FOR DIRECTORY CONTAINING TIFF FILES.
2.PROVIDE ABSOLUTE/RELATIVE PATH TO DIRECTORY FOR OUTPUT.[OPTIONAL]
ONLY"
	exit
fi

TIFF_FILES_LIST=`ls $1`	#contains all the tiff files

mkdir -p $HTML_PATH $JPEG_PATH $GIF_PATH

# creates main html which lists all the issues

> $HTML_PATH/main.html
echo "<!DOCTYPE html>
<html>
	<head>
		<title>LIST OF ISSUES BETWEEN 1990-1991</title>
	</head>
	<body>
		" > $HTML_PATH/main.html
for TIFF_FILENAME in $TIFF_FILES_LIST
do
#	echo "TIFF_FILENAME: $TIFF_FILENAME"
	ISSUENAME=`basename $TIFF_FILENAME .tif`
#	echo "ISSUENAME:"$ISSUENAME""
	
# 	creates each individual file for each issue 

	> $HTML_PATH/$ISSUENAME.html
	echo "<!DOCTYPE html>
<html>
	<head>
		<title>$ISSUENAME</title>
	</head>
	<body>
		"> $HTML_PATH/$ISSUENAME.html

	mkdir -p $JPEG_PATH/$ISSUENAME
	mkdir -p $HTML_PATH/$ISSUENAME
	mkdir -p $GIF_PATH/$ISSUENAME

	convert $1/$TIFF_FILENAME $JPEG_PATH/$ISSUENAME/$ISSUENAME.jpeg

	for JPEG_FILENAME in `ls $JPEG_PATH/$ISSUENAME`
	do
#		echo "JPEG_FILENAME:$JPEG_FILENAME"
		
		JPEG_PER_PAGE=`basename $JPEG_FILENAME .jpeg`
		HTML_PER_PAGE=$JPEG_PER_PAGE.html
		GIF_PER_PAGE=$JPEG_PER_PAGE.gif
		
		convert $JPEG_PATH/$ISSUENAME/$JPEG_FILENAME $GIF_PATH/$ISSUENAME/$GIF_PER_PAGE
		echo "<p><a href=\"$ISSUENAME/$HTML_PER_PAGE\"><img src=\"../GIF_FILES/$ISSUENAME/$GIF_PER_PAGE\" alt=\"$JPEG_PER_PAGE\" style=\"width:200px;height:200px;\">$JPEG_PER_PAGE</a></p>" >> $HTML_PATH/$ISSUENAME.html	
#		echo "JPEG_PER_PAGE:$JPEG_PER_PAGE"
#		echo "HTML_PER_PAGE:$HTML_PER_PAGE"

#		creates individual html files for each page
		
		> $HTML_PATH/$ISSUENAME/$HTML_PER_PAGE
		echo "<!DOCTYPE html>
	<html>
		<head>
			<title>$JPEG_PER_PAGE</title>
		</head>
		<body>
			<img src=\"../../JPEG_FILES/$ISSUENAME/$JPEG_FILENAME\" alt=$JPEG_PER_PAGE>
			<p><a href=\"../main.html\">BACK TO MAIN</a></p>
			<p><a href=\"../$ISSUENAME.html\">BACK TO ISSUE MENU</a></p>
		</body>
	</html>" >> $HTML_PATH/$ISSUENAME/$HTML_PER_PAGE
	 done
	echo "			<p><a href=\"main.html\">BACK TO MAIN</a></p>
	</body>
</html>" >> $HTML_PATH/$ISSUENAME.html
	
	echo "<p><a href=\"$ISSUENAME.html\">Issue of $ISSUENAME</a></p>" >> $HTML_PATH/main.html
done 
	echo "	</body>
</html>" >> $HTML_PATH/main.html
exit
