#!/bin/sh
TIFF_FILES_LIST=`ls TIFF_FILES`	#contains all the tiff files

mkdir -p HTML_FILES JPEG_FILES

# creates main html which lists all the issues

> HTML_FILES/main.html
echo "<!DOCTYPE html>
<html>
	<head>
		<title>LIST OF ISSUES BETWEEN 1990-1991</title>
	</head>
	<body>
		" > HTML_FILES/main.html
for TIFF_FILENAME in $TIFF_FILES_LIST
do
#	echo "TIFF_FILENAME: $TIFF_FILENAME"
	ISSUENAME=`basename $TIFF_FILENAME .tif`
#	echo "ISSUENAME:"$ISSUENAME""
	
# 	creates each individual file for each issue 

	> HTML_FILES/$ISSUENAME.html
	echo "<!DOCTYPE html>
<html>
	<head>
		<title>$ISSUENAME</title>
	</head>
	<body>
		"> HTML_FILES/$ISSUENAME.html
	mkdir -p JPEG_FILES/$ISSUENAME
	mkdir -p HTML_FILES/$ISSUENAME
	convert TIFF_FILES/$TIFF_FILENAME JPEG_FILES/$ISSUENAME/$ISSUENAME.jpeg

	for JPEG_FILENAME in `ls JPEG_FILES/$ISSUENAME`
	do
#		echo "JPEG_FILENAME:$JPEG_FILENAME"
		
		JPEG_PER_PAGE=`basename $JPEG_FILENAME .jpeg`
		HTML_PER_PAGE=$JPEG_PER_PAGE.html

		echo "<p><a href=\"$ISSUENAME/$HTML_PER_PAGE\">$JPEG_PER_PAGE</a></p>" >> HTML_FILES/$ISSUENAME.html	
#		echo "JPEG_PER_PAGE:$JPEG_PER_PAGE"
#		echo "HTML_PER_PAGE:$HTML_PER_PAGE"

#		creates individual html files for each page
		
		> HTML_FILES/$ISSUENAME/$HTML_PER_PAGE
		echo "<!DOCTYPE html>
	<html>
		<head>
			<title>$JPEG_PER_PAGE</title>
		</head>
		<body>
			<img src=\"../../JPEG_FILES/$ISSUENAME/$JPEG_FILENAME\" alt=$JPEG_PER_PAGE>
			<p><a href=\"../main.html\">BACK TO MAIN</a></p>
			<p><a href=\"../$ISSUENAME.html\">BACK TO ISSUE MENU</a></p>
		</body>
	</html>" >> HTML_FILES/$ISSUENAME/$HTML_PER_PAGE
	 done
	echo "			<p><a href=\"main.html\">BACK TO MAIN</a></p>
	</body>
</html>" >> HTML_FILES/$ISSUENAME.html
	
	echo "<p><a href=\"$ISSUENAME.html\">Issue of $ISSUENAME</a></p>" >> HTML_FILES/main.html
done 
	echo "	</body>
</html>" >> HTML_FILES/main.html
exit
